-- MySQL Script generated by MySQL Workbench
-- Thu Aug  5 20:14:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vacancies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vacancies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vacancies` DEFAULT CHARACTER SET utf8 ;
USE `vacancies` ;

-- -----------------------------------------------------
-- Table `vacancies`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies`.`roles` (
  `role_id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacancies`.`user_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies`.`user_statuses` (
  `status_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`),
  UNIQUE INDEX `status_id_UNIQUE` (`status_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacancies`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `icon` BLOB NULL,
  `role_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `userscol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `role_idx` (`role_id` ASC) VISIBLE,
  INDEX `status_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `role`
    FOREIGN KEY (`role_id`)
    REFERENCES `vacancies`.`roles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `vacancies`.`user_statuses` (`status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacancies`.`vacancy_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies`.`vacancy_status` (
  `status_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacancies`.`vacancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies`.`vacancies` (
  `vacancy_id` INT NOT NULL AUTO_INCREMENT,
  `logo` BLOB NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `salary` DECIMAL NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`vacancy_id`),
  UNIQUE INDEX `vacancy_id_UNIQUE` (`vacancy_id` ASC) VISIBLE,
  INDEX `vacancy_status_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `vacancy_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `vacancies`.`vacancy_status` (`status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacancies`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancies`.`feedbacks` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `vacancy_id` INT NOT NULL,
  `letter` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`feedback_id`),
  UNIQUE INDEX `feedback_id_UNIQUE` (`feedback_id` ASC) VISIBLE,
  INDEX `user_key_idx` (`employee_id` ASC) VISIBLE,
  INDEX `vacancy_key_idx` (`vacancy_id` ASC) VISIBLE,
  CONSTRAINT `user_key`
    FOREIGN KEY (`employee_id`)
    REFERENCES `vacancies`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vacancy_key`
    FOREIGN KEY (`vacancy_id`)
    REFERENCES `vacancies`.`vacancies` (`vacancy_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
