package edu.epam.webproject.controller.command;

public enum CommandType {
    SIGN_IN_COMMAND,
    SIGN_UP_COMMAND,
    LOG_OUT_COMMAND,
    GO_TO_ABOUT_PAGE_COMMAND,
    GO_TO_SIGN_UP_PAGE_COMMAND,
    GO_TO_SIGN_IN_PAGE_COMMAND,
    GO_TO_ALL_USERS_PAGE_COMMAND,
    GO_TO_ALL_RELEVANT_VACANCIES_PAGE_COMMAND,
    GO_TO_ALL_IRRELEVANT_VACANCIES_PAGE_COMMAND,
    GO_TO_USER_ACCOUNT_PAGE_COMMAND,
    CHANGE_USER_STATUS_COMMAND,
    CHANGE_VACANCY_STATUS_COMMAND,
    CHANGE_LOCALE_COMMAND,
    ACTIVATE_ACCOUNT_COMMAND,
    GO_TO_ADD_NEW_VACANCY_PAGE_COMMAND,
    GO_TO_VACANCY_PAGE_COMMAND,
    GO_TO_ADMIN_ACCOUNT_PAGE_COMMAND,
    GO_TO_CHANGE_USER_PASSWORD_PAGE_COMMAND,
    RESPOND_COMMAND,
    ADD_NEW_VACANCY_COMMAND,
    DEFAULT
}
